"""Tool-calling agent - Azure Functions entry point.

Registers the compiled tool-calling graph, then wires the OpenAPI bridge so the
graph's routes appear in a spec generated by ``azure-functions-openapi-python``.

Run from this directory:
    func start
"""

from graph import compiled_graph

from azure_functions_langgraph import LangGraphApp
from azure_functions_langgraph.openapi import register_with_openapi

# Default auth_level is AuthLevel.FUNCTION — deployed endpoints require a
# function key (`?code=<FUNCTION_KEY>` or the `x-functions-key` header).
langgraph_app = LangGraphApp()
langgraph_app.register(
    graph=compiled_graph,
    name="tool_calling_agent",
    description="An Azure OpenAI agent that calls tools (order lookup, weather) in a ToolNode loop",
)

# OpenAPI bridge (issue #411): forward this graph's route metadata to
# azure-functions-openapi-python so the endpoints show up in the generated spec
# and are Swagger-testable. `azure-functions-openapi-python` is an EXAMPLE-ONLY
# dependency (see requirements.txt); the import stays behind the package's own
# ImportError guard inside register_with_openapi.
count = register_with_openapi(langgraph_app)
print(f"[tool_calling_agent] forwarded {count} route(s) to azure-functions-openapi-python")

app = langgraph_app.function_app
